.TH "./sutra" "1" "2014 02 25" "sea (erat.simon@gmail.com)"

.SH NAME
./sutra (0.1)

.SH SYNOPSIS
\fB./sutra\fP [options] [arguments]
.br
Example: ./sutra 
.br
Where options are:
.IP "\fB-h|help\fP"
This screen
.IP "\fB-a|about\fP"
Prints an overview of installed langauges, their books, chapters and amount of verses.

.SH DESCRIPTION
.PP
Some descriptional text

.SH LICENSE
GNU Lesser General Public License (LGPL)
.br
http://www.gnu.org/licenses/lgpl.html

.SH CONTACT

.br

