#!/bin/sh
#	Author: 	Simon Arjuna Erat (sea)
#	License:	GPL3
#	Contact:	erat.simon@gmail.com
#	Changed:	2014.02.25
#	Created:	2014.03.02
#
#	Variable defaults
#
	source tui
	script_version=0.2
	ME="$(basename $0)"
	DIR="/usr/share/$ME"
	OLD="$(pwd)"
	[ ! -z ${TITLE[@]} ] && unset TITLE[@]
	help_text="\n$ME ($script_version)
		\r$TITLE
		\rUsage: $ME [options] [arguments]
		\rWhere options are:
		\r\t-h|help \tThis screen
		\r\t-a|about\tPrints information about all installed language packes
		\r\t\t\tand therefore of all installed books and their chapters & verses count.
		\r"
	ARGS=(${@})
	ARGS_COUNT=$#
	[ -z $WIDTH ] && WIDTH=$(tput cols)
	LEN=$[ 2 * ${#BORDER_LEFT} ]
	WIDTH=$[ $WIDTH - $LEN ]
	CONFIG="$HOME/.config/motd-sutra.conf"
	
#
#	Empty configuration values,
#	check for $CONFIG and retrieve values if exist
#	create and define default configuration otherwise
#
	myLanguage=""
	myBook=""
	if [  -f "$CONFIG" ]
	then	source "$CONFIG"
	else	langs=( $(for f in $(ls -d *);do [ -d $f ] && printf "$f ";done) )
		if [ "German" = "$(printf "$langs")" ]
		then	myLanguage=$(printf "$langs")
		else	tui-echo "Please choose a language:"
			select myLanguage in $langs;do break;done
		fi
		printf "# Configurationfile from $ME ($script_version) - $TITLE
# Created in the year $(date +'%Y within %B on %d @ %H:%M')
myLanguage=\"$myLanguage\"
myBook=\"\"" > $CONFIG
		source "$CONFIG"
	fi
#
#	Load array file with title caption
#
	LANGUAGE="$DIR/lang/${myLanguage,,}" ; 	source "$LANGUAGE"
	BOOKS_DIR="$DIR/lang/$myLanguage"
	myTitle="${TITLE[$myLanguage]}"
	cd "$BOOKS_DIR" ; BOOKS_LIST="$(ls -ld *|awk '{print $9}')"
#
#	Variable handling
#
	server_info="$1"
	while getopts "a:(about)h:(help)": name
	do 	case $name in
		a|about)
			tui-header "$ME ($script_version)" "written by: Simon Arjuna Erat (sea)"
			for lang in $DIR/lang/[A-Z]*;do
				books=""
				this="$(basename $lang)"
				LANG="$this"
				this="${this:0:1}"
				this_cap="${this^^}"
				if [ "$this" = "$this_cap" ]
				then	tui-title "${TITLE[$LANG]}"
					tui-title "${lblAboutTitle[$LANG]}" #"Installed Languages & Books"
					tui-echo "${lblLanguage[$LANG]}:" "$LANG"
					source "${lang,,}"
					tui-echo "${LangRevlbl[$LANG]}:" 	"${LangRevval[$LANG]}"
					tui-echo "Authors:" 			"${LangAuthors[@]}" 
					tui-echo "${LangRevCommentlbl[$LANG]}" 	"${LangRevComment[$LANG]}"
					
					for b in "$lang"/*;do 
						books+=" $b"
						tui-title "${lblTitle[$LANG]}: ${b:(${#lang} + 1)}"
						CHAPTERS=( "$b"/* )
						unset chaps[@]
						for CHAPTER in "${CHAPTERS[@]}" ;do
							cd "${CHAPTER}"
							chaps=( $(ls) )
							tui-echo "${lblChapter[$LANG]}: ${CHAPTER:${#b} + 1}" \
								"${lblVers[$LANG]}: ${#chaps[@]}"  
						done
					done
					
				fi
			done
			exit 0			;;
		h|help)
			printf "$help_text"
			exit $RET_HELP	;;
		o|ow|overwrite)
			server_info="$OPTARG"
			mode=ow			;;
		u|um|umount|unmount)
			server_info="$OPTARG"
			mode=u			;;
		?)	printf "$help_text"
			exit $RET_FAIL	;;
		esac
	done
	
	shift $(($OPTIND - 1))
	ARGS=(${*})
#
#	Functions
#
	rnd() { # MAX [ MIN=0 ]
	# Returns a random number upto MAX, 
	# or if provided, between MIN and MAX.
	#
	#	Arguments
	#
		[ -z $1 ] && printf "\rEE$0::Must provide MAX value!\n" && exit 1
		count=0
		min=0
		task=todo
		rnd=$RANDOM
		[ ! -z $2 ] && 
			(( if [ $1 -gt $2 ] ;then min=$2;max=$1;else min=$1;max=$2;fi )) || \
			max=$1
	#
	#	Action
	#
		while [ $rnd -gt $max ]  #&& (( [ ! -z $2 ] && [ $min -gt $rnd ] ))
		do	rnd=$(($RANDOM*$max/$RANDOM))
		done
		printf $rnd
	}
	GetRndfromFolder() { # DIRECTORY
	# Change to DIRECTORY (& back when done),
	# returns a random item from its content (file-,foldername)
		unset ALL[@]
		old="$(pwd)"
		if [ -d "$1" ] 
		then	cd "$1"
		else	tui-status 1 "${lblNoPath[$myLanguage]} ($1)";exit 1
		fi
		ALL=( * )
		TOTAL=$[ ${#ALL[@]} ]
		STR="${ALL[$(rnd $[ $TOTAL - 1 ])]}"
		printf "$STR"
		cd $old
	}
#
#	Verify we have a book to look for sutra
#
	if [ -z $myBook ]
	then	if [ "$(printf $BOOKS_LIST|wc|awk '{print $2}')" -eq 1 ]
		then	TB="$(printf $BOOKS_LIST)"
			sed s,myBook=\"\",myBook=\"$TB\",g -i $CONFIG
			tui-status $? "${lblChooseBookOne[$myLanguage]}"	&& \
				source "$CONFIG" || exit 1
		else	tui-echo "${lblChooseBook[$myLanguage]}"
			select TB in $BOOKS_LIST;do break;done
			sed s,myBook=\"\",myBook=\"$TB\",g -i $CONFIG
			tui-status $? "$TB ${lblChooseBookDone[$myLanguage]}"	&& \
				source "$CONFIG" || exit 1
		fi
	fi
#
#	Get a random chapter from within the book
#	and then choose a random sutra from that chapter-dir
#
	CHAPTER=$(GetRndfromFolder "$BOOKS_DIR/$myBook")
	SUTRA=$(GetRndfromFolder "$BOOKS_DIR/$myBook/$CHAPTER")
#
#	Display to user : Header
#
	tui-header	"$myTitle : $myBook" \
		 	"$ME ($script_version), ${LangRevlbl[$myLanguage]}: ${LangRevval[$myLangauge]}"
	tui-title "$SUTRA) $CHAPTER"
#
#	Display to user : Actual Sutra
#
	case $myLanguage in
	German)	CONTENT=$(cat "$BOOKS_DIR/$myBook/$CHAPTER/$SUTRA"|sed s,ä,ae,g|sed s,ö,oe,g|sed s,ü,ue,g|sed s,ã,a,g|sed s,ñ,n,g)
		# Note: the 'sed's are just to 'align' tui-echo's output 
		# 	as long it has issues with 'special-chars' (äöü,ãñ,etc)
		WIDTH=$[ $WIDTH - 5 ]
		;;
	*)	CONTENT=$(cat "$BOOKS_DIR/$myBook/$CHAPTER/$SUTRA")
		;;
	esac
	while [ ! "" = "$CONTENT" ];do
		line=$(printf "${CONTENT:0:$WIDTH}"|sed s,' '$,,g) # sed is additional attemp to remove trailing spaces
		tui-echo "$line"
		CONTENT="${CONTENT:${#line}}"
	done
#
#	Return to old/origin location
#
	cd $OLD
